spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: microcare
    password: microcare_pass
    virtual-host: /

eureka:
  client:
    enabled: false

app:
  rabbitmq:
    exchange: appointment.exchange
    dlx: appointment.dlx
    queue:
      billing-invoice: billing.invoice.queue
    dlq:
      billing-invoice: billing.invoice.dlq
    routing-key:
      appointment-confirmed: appointment.confirmed
    max-retries: 3
